### ISSUE TITLE
minikube mount options

### ISSUE THREAD

**Issue by nicks** [tilt-dev/ctlptl#127]
Currently, you can mount a local folder into the minikube VM with something like:

```
minikube start --mount --mount-string="$PWD:/home" --driver docker
```

ctlptl should support something like this. The most bare-bones way to support it would be to have a pass-through way to set minikube options, as described here: https://github.com/tilt-dev/ctlptl/issues/86

But one of the goals of ctlptl is to have apis that are a bit abstracted above the underlying implementation engine (whether it's a VM vs a docker container, or Kind vs Minikube), so i wonder if we could offer a better config-based option that would also work on Kind

**Comment by stabai** [comment]
Is there any workaround for this? It seems like the only current way to do mounts is to have a script that runs after ctlptl to run [minikube mount](https://minikube.sigs.k8s.io/docs/commands/mount/)?

**Comment by nicks** [comment]
this is implemented:

```
ctlptl apply -f - <<EOF
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: minikube
minikube:
  startFlags:
    - "--mount"
    - "--mount-string=$(pwd):/home"
EOF
```

**Comment by stabai** [comment]
Awesome, thanks!

Am I correct in assuming the `$(pwd)` part doesn't work if you're applying a config from a file?

I have the following `ctlptl.yaml` file:

```yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: actual-tilt
product: minikube
minikube:
  startFlags:
    - "--mount"
    - "--mount-string=$(pwd)/.data:/var/lib/volumes"
    - "--addons=ingress"
    - "--disk-size=40g"
registry: local-docker-registry
minCPUs: 4
```

And when I try to run it with `ctlptl apply -f ctlptl.yaml`, I get the following error:

```
docker: Error response from daemon: create $(pwd): "$(pwd)" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

I also tried `$PWD` and `.`, but got the same thing for those too. Is there just no way to do a relative path using a YAML file?
