### ISSUE TITLE
Creating cluster: No available kindest/node versions for kind version v0.11.1.

### ISSUE THREAD

**Issue by Mattes83** [tilt-dev/ctlptl#129]
Hi there,

I am trying to create a cluster with ctlptl with the following config: 

```yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kubernetesVersion: 1.20.2
kindV1Alpha4Cluster:
  name: operator-debug
  networking:
    apiServerAddress: 0.0.0.0
    apiServerPort: 8443
    ipFamily: ipv4
  nodes:
    - role: control-plane
    - role: worker
```

When I do ``ctlptl apply -f kind-cluster.yaml`` I get the following error:
creating cluster: No available kindest/node versions for kind version v0.11.1.
Please file an issue: https://github.com/tilt-dev/ctlptl/issues/new

I am running this inside wsl2 with Docker Desktop and kind version is kind v0.11.1 go1.16.4 linux/amd64

Best regards
