### ISSUE TITLE
support for rancher desktop as VM manager

### ISSUE THREAD

**Issue by nicks** [tilt-dev/ctlptl#153]
currently, ctlptl uses Docker Desktop as the primary VM manager on Windows/macos.

As more people use Rancher Desktop, we may need to add support for using it as a VM manager too.

**Comment by nicks** [comment]
@TimothyLoyer I haven't really spent much time investigating whether RD has the APIs we would need to support this. 

Getting Docker Desktop to support took a bunch of research, and uses some undocumented APIs.

So certainly wouldn't reject a contribution of Rancher Desktop support, just that it's probably non-trivial and the tilt team has already been burned a couple times on adding support for Rancher Desktop APIs that changed out from under us.

**Comment by TimothyLoyer** [comment]
> So certainly wouldn't reject a contribution of Rancher Desktop support, just that it's probably non-trivial and the tilt team has already been burned a couple times on adding support for Rancher Desktop APIs that changed out from under us.

That makes sense, thank you for the reply and all your hard work!

**Comment by benjaminpreiss** [comment]
Hey everyone!

Loving `ctlptl`! ... But I'd prefer to use rancher desktop instead of docker desktop :)
It seems rancher desktop is still not supported, can that be?

Running `ctlptl apply -f ctlptl.yaml` results in:

```
❯ ctlptl apply -f ctlptl.yaml 
Creating registry "ctlptl-registry"...
registry.ctlptl.dev/ctlptl-registry created
reading docker-desktop settings: Get "http://localhost/app/settings?format=grouped": dial unix /Users/********/Library/Containers/com.docker.docker/Data/backend.sock: connect: connection refused
```

with

```yaml
# ctlptl.yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
```
