### ISSUE TITLE
Mount host directories on a virtual node (kind)

### ISSUE THREAD

**Issue by Effsy** [tilt-dev/ctlptl#202]
Kind allows you to mount host directories on a kind node. https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts

For example:

```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/bill/work/foo
        containerPath: /foo
```
Then run:
```
kind create cluster --config kind-config.yaml
```

This currently doesn't seem possible with ctlptl. What are the other options?

Related issue with minikube (to solve this generically) https://github.com/tilt-dev/ctlptl/issues/127
