### ISSUE TITLE
The cascade flag seems to be backwards

### ISSUE THREAD

**Issue by tylermichael** [tilt-dev/ctlptl#243]
My config file looks like

**kind-config.yaml**:
```yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 10000
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: k8s
  nodes:
    - role: control-plane
      extraMounts:
        - hostPath: ../
          containerPath: /acme
```

Running `ctlptl apply -f kind-config.yaml` brings everything up ok.

Running `ctlptl delete -f kind-config.yaml` deletes the k8s cluster and the registry even though `--cascade` says it defaults to false.

Running `ctlptl delete -f kind-config.yaml --cascade true` just deletes the k8s cluster and leaves my registry.

Based off of this [PR](https://github.com/tilt-dev/ctlptl/pull/221), `--cascade true` seems like it should delete everything.
