### ISSUE TITLE
Support for ingress with kind

### ISSUE THREAD

**Issue by dparbhakar** [tilt-dev/ctlptl#286]
Hello,

I am trying to get nginx-ingress-controller to work with a local kind cluster deployed by ctlptl, following these docs : https://kind.sigs.k8s.io/docs/user/ingress/

How can I proceed to this configuration using ctlptl ?

Thanks,

**Comment by nicks** [comment]
Check out the API docs:
https://pkg.go.dev/github.com/tilt-dev/ctlptl/pkg/api#Cluster

It will look like:

```
cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
kindV1Alpha1Cluster:
  nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
EOF
```
