### ISSUE TITLE
Registry image is overridden when referencing registry from cluster

### ISSUE THREAD

**Issue by RedbackThomson** [tilt-dev/ctlptl#344]
I am attempting to apply the following manifest:

```yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5001
listenAddress: 127.0.0.1
image: <my-private-registry-image>
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  ...
```

However, it appears that when applying the `Cluster` type, `ctlptl` will override the image of the private registry back to the default `docker/registry:2` image. Ideally, it would not change anything about the registry and use it as it is.

In order to get around this for the moment, I am first applying the `Cluster` (which creates `ctlptl-registry` with the default registry image) and then applying the `Registry` to override it back to use my private image.
