### ISSUE TITLE
failed to create HA cluster registry 

### ISSUE THREAD

**Issue by nhphu** [tilt-dev/ctlptl#356]
`OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
configuring registry: exit status 126`

yaml file: 

```
kind: Cluster
apiVersion: ctlptl.dev/v1alpha1
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
 ```
