### ISSUE TITLE
Can't connect to HA cluster after reboot

### ISSUE THREAD

**Issue by nhphu** [tilt-dev/ctlptl#358]
#357 

reproduce:

1. create HA cluster with ctlptl

```
kind: Cluster
apiVersion: ctlptl.dev/v1alpha1
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
```
2. Reboot computer
3. start haproxy container
4. tilt up

```
Cluster status error: Tilt encountered an error connecting to your Kubernetes cluster:
	client rate limiter Wait returned an error: context deadline exceeded - error from a previous attempt: EOF
You will need to restart Tilt after resolving the issue.
```

There is no error when creating an HA cluster directly with the 'kind create' command.
