### ISSUE TITLE
Support apple M1

### ISSUE THREAD

**Issue by sayjeyhi** [tilt-dev/ctlptl#97]
I am using `ctlptl` to create my k8s cluster using `kind`. but because I am running k8s on MacBook M1.
I got some problems with creating a cluster using kind.

I find a solution in this StackOverflow answer comments: https://stackoverflow.com/a/65864116/4718253
which advice using another image to create a kind cluster like this:
```
kind create cluster --image rossgeorgiev/kind-node-arm64:v1.20.0
```

Now, If I don't know how should I change my ctlptl config to use that image instead!
here is my `config.yaml` file:
```yaml
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: extraa
  nodes:
    - role: control-plane
```

**Comment by nicks** [comment]
Hi @sayjeyhi ! You're mostly on the right track...it should work if you change the config to:

```
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
      image: rossgeorgiev/kind-node-arm64:v1.20.0
```

Here's the Kind cluster config format: https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster
